#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICEData")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICEDataConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Result> Results
	{
		get
		{
			return this.GetTable<Result>();
		}
	}
	
	public System.Data.Linq.Table<CivilSubMaster> CivilSubMasters
	{
		get
		{
			return this.GetTable<CivilSubMaster>();
		}
	}
	
	public System.Data.Linq.Table<ArchiSubMaster> ArchiSubMasters
	{
		get
		{
			return this.GetTable<ArchiSubMaster>();
		}
	}
	
	public System.Data.Linq.Table<APartI> APartIs
	{
		get
		{
			return this.GetTable<APartI>();
		}
	}
	
	public System.Data.Linq.Table<CPartI> CPartIs
	{
		get
		{
			return this.GetTable<CPartI>();
		}
	}
	
	public System.Data.Linq.Table<CPartII> CPartIIs
	{
		get
		{
			return this.GetTable<CPartII>();
		}
	}
	
	public System.Data.Linq.Table<ResultCPartI> ResultCPartIs
	{
		get
		{
			return this.GetTable<ResultCPartI>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Result")]
public partial class Result
{
	
	private string _ExamSeason;
	
	private string _RSID;
	
	private string _SubID;
	
	private string _GetMarks;
	
	private string _Status;
	
	private string _RSession;
	
	private string _ATime;
	
	private string _IMID;
	
	private string _ECourse;
	
	private string _Part;
	
	private string _SID;
	
	private string _EStatus;
	
	private string _RCourse;
	
	private string _RPart;
	
	public Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamSeason", DbType="NVarChar(50)")]
	public string ExamSeason
	{
		get
		{
			return this._ExamSeason;
		}
		set
		{
			if ((this._ExamSeason != value))
			{
				this._ExamSeason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSID", DbType="NVarChar(10)")]
	public string RSID
	{
		get
		{
			return this._RSID;
		}
		set
		{
			if ((this._RSID != value))
			{
				this._RSID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(10)")]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetMarks", DbType="NVarChar(10)")]
	public string GetMarks
	{
		get
		{
			return this._GetMarks;
		}
		set
		{
			if ((this._GetMarks != value))
			{
				this._GetMarks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSession", DbType="NVarChar(7)")]
	public string RSession
	{
		get
		{
			return this._RSession;
		}
		set
		{
			if ((this._RSession != value))
			{
				this._RSession = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATime", DbType="NVarChar(5)")]
	public string ATime
	{
		get
		{
			return this._ATime;
		}
		set
		{
			if ((this._ATime != value))
			{
				this._ATime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMID", DbType="NVarChar(15)")]
	public string IMID
	{
		get
		{
			return this._IMID;
		}
		set
		{
			if ((this._IMID != value))
			{
				this._IMID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECourse", DbType="NVarChar(50)")]
	public string ECourse
	{
		get
		{
			return this._ECourse;
		}
		set
		{
			if ((this._ECourse != value))
			{
				this._ECourse = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Part", DbType="NVarChar(50)")]
	public string Part
	{
		get
		{
			return this._Part;
		}
		set
		{
			if ((this._Part != value))
			{
				this._Part = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(50)")]
	public string SID
	{
		get
		{
			return this._SID;
		}
		set
		{
			if ((this._SID != value))
			{
				this._SID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EStatus", DbType="NVarChar(50)")]
	public string EStatus
	{
		get
		{
			return this._EStatus;
		}
		set
		{
			if ((this._EStatus != value))
			{
				this._EStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCourse", DbType="NVarChar(50)")]
	public string RCourse
	{
		get
		{
			return this._RCourse;
		}
		set
		{
			if ((this._RCourse != value))
			{
				this._RCourse = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPart", DbType="NVarChar(10)")]
	public string RPart
	{
		get
		{
			return this._RPart;
		}
		set
		{
			if ((this._RPart != value))
			{
				this._RPart = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CivilSubMaster")]
public partial class CivilSubMaster
{
	
	private int _SN;
	
	private string _SubID;
	
	private string _SubName;
	
	private System.Nullable<int> _MaxMark;
	
	private System.Nullable<int> _MinMark;
	
	private System.Nullable<int> _First;
	
	private System.Nullable<int> _Lvl;
	
	private string _Section;
	
	private System.Nullable<System.DateTime> _Date;
	
	private string _SubjectType;
	
	private string _CourseID;
	
	private string _Status;
	
	public CivilSubMaster()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int SN
	{
		get
		{
			return this._SN;
		}
		set
		{
			if ((this._SN != value))
			{
				this._SN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(50)")]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubName", DbType="NVarChar(MAX)")]
	public string SubName
	{
		get
		{
			return this._SubName;
		}
		set
		{
			if ((this._SubName != value))
			{
				this._SubName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxMark", DbType="Int")]
	public System.Nullable<int> MaxMark
	{
		get
		{
			return this._MaxMark;
		}
		set
		{
			if ((this._MaxMark != value))
			{
				this._MaxMark = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinMark", DbType="Int")]
	public System.Nullable<int> MinMark
	{
		get
		{
			return this._MinMark;
		}
		set
		{
			if ((this._MinMark != value))
			{
				this._MinMark = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First", DbType="Int")]
	public System.Nullable<int> First
	{
		get
		{
			return this._First;
		}
		set
		{
			if ((this._First != value))
			{
				this._First = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lvl", DbType="Int")]
	public System.Nullable<int> Lvl
	{
		get
		{
			return this._Lvl;
		}
		set
		{
			if ((this._Lvl != value))
			{
				this._Lvl = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="NVarChar(50)")]
	public string Section
	{
		get
		{
			return this._Section;
		}
		set
		{
			if ((this._Section != value))
			{
				this._Section = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectType", DbType="NVarChar(50)")]
	public string SubjectType
	{
		get
		{
			return this._SubjectType;
		}
		set
		{
			if ((this._SubjectType != value))
			{
				this._SubjectType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50)")]
	public string CourseID
	{
		get
		{
			return this._CourseID;
		}
		set
		{
			if ((this._CourseID != value))
			{
				this._CourseID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ArchiSubMaster")]
public partial class ArchiSubMaster
{
	
	private int _SN;
	
	private string _SubID;
	
	private string _SubName;
	
	private System.Nullable<int> _MaxMark;
	
	private System.Nullable<int> _MinMark;
	
	private System.Nullable<int> _First;
	
	private System.Nullable<int> _Lvl;
	
	private string _Section;
	
	private System.Nullable<System.DateTime> _Date;
	
	private string _SubjectType;
	
	private string _CourseID;
	
	private string _Status;
	
	public ArchiSubMaster()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int SN
	{
		get
		{
			return this._SN;
		}
		set
		{
			if ((this._SN != value))
			{
				this._SN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(50)")]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubName", DbType="NVarChar(MAX)")]
	public string SubName
	{
		get
		{
			return this._SubName;
		}
		set
		{
			if ((this._SubName != value))
			{
				this._SubName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxMark", DbType="Int")]
	public System.Nullable<int> MaxMark
	{
		get
		{
			return this._MaxMark;
		}
		set
		{
			if ((this._MaxMark != value))
			{
				this._MaxMark = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinMark", DbType="Int")]
	public System.Nullable<int> MinMark
	{
		get
		{
			return this._MinMark;
		}
		set
		{
			if ((this._MinMark != value))
			{
				this._MinMark = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First", DbType="Int")]
	public System.Nullable<int> First
	{
		get
		{
			return this._First;
		}
		set
		{
			if ((this._First != value))
			{
				this._First = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lvl", DbType="Int")]
	public System.Nullable<int> Lvl
	{
		get
		{
			return this._Lvl;
		}
		set
		{
			if ((this._Lvl != value))
			{
				this._Lvl = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="NVarChar(50)")]
	public string Section
	{
		get
		{
			return this._Section;
		}
		set
		{
			if ((this._Section != value))
			{
				this._Section = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectType", DbType="NVarChar(50)")]
	public string SubjectType
	{
		get
		{
			return this._SubjectType;
		}
		set
		{
			if ((this._SubjectType != value))
			{
				this._SubjectType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50)")]
	public string CourseID
	{
		get
		{
			return this._CourseID;
		}
		set
		{
			if ((this._CourseID != value))
			{
				this._CourseID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APartI")]
public partial class APartI
{
	
	private string _ExamSeason;
	
	private string _EStatus;
	
	private string _SubID;
	
	private string _Marks;
	
	private string _RStatus;
	
	private string _Session;
	
	private string _SID;
	
	private string _Course;
	
	private string _Part;
	
	public APartI()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamSeason", DbType="NVarChar(50)")]
	public string ExamSeason
	{
		get
		{
			return this._ExamSeason;
		}
		set
		{
			if ((this._ExamSeason != value))
			{
				this._ExamSeason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EStatus", DbType="NVarChar(50)")]
	public string EStatus
	{
		get
		{
			return this._EStatus;
		}
		set
		{
			if ((this._EStatus != value))
			{
				this._EStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Marks
	{
		get
		{
			return this._Marks;
		}
		set
		{
			if ((this._Marks != value))
			{
				this._Marks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStatus", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
	public string RStatus
	{
		get
		{
			return this._RStatus;
		}
		set
		{
			if ((this._RStatus != value))
			{
				this._RStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Session
	{
		get
		{
			return this._Session;
		}
		set
		{
			if ((this._Session != value))
			{
				this._Session = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SID
	{
		get
		{
			return this._SID;
		}
		set
		{
			if ((this._SID != value))
			{
				this._SID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(50)")]
	public string Course
	{
		get
		{
			return this._Course;
		}
		set
		{
			if ((this._Course != value))
			{
				this._Course = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Part", DbType="NVarChar(50)")]
	public string Part
	{
		get
		{
			return this._Part;
		}
		set
		{
			if ((this._Part != value))
			{
				this._Part = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CPartI")]
public partial class CPartI
{
	
	private string _ExamSeason;
	
	private string _EStatus;
	
	private string _SubID;
	
	private string _Marks;
	
	private string _RStatus;
	
	private string _Session;
	
	private string _SID;
	
	private string _Course;
	
	private string _Part;
	
	public CPartI()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamSeason", DbType="NVarChar(50)")]
	public string ExamSeason
	{
		get
		{
			return this._ExamSeason;
		}
		set
		{
			if ((this._ExamSeason != value))
			{
				this._ExamSeason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EStatus", DbType="NVarChar(50)")]
	public string EStatus
	{
		get
		{
			return this._EStatus;
		}
		set
		{
			if ((this._EStatus != value))
			{
				this._EStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Marks
	{
		get
		{
			return this._Marks;
		}
		set
		{
			if ((this._Marks != value))
			{
				this._Marks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStatus", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
	public string RStatus
	{
		get
		{
			return this._RStatus;
		}
		set
		{
			if ((this._RStatus != value))
			{
				this._RStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Session
	{
		get
		{
			return this._Session;
		}
		set
		{
			if ((this._Session != value))
			{
				this._Session = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SID
	{
		get
		{
			return this._SID;
		}
		set
		{
			if ((this._SID != value))
			{
				this._SID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(50)")]
	public string Course
	{
		get
		{
			return this._Course;
		}
		set
		{
			if ((this._Course != value))
			{
				this._Course = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Part", DbType="NVarChar(50)")]
	public string Part
	{
		get
		{
			return this._Part;
		}
		set
		{
			if ((this._Part != value))
			{
				this._Part = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CPartII")]
public partial class CPartII
{
	
	private string _ExamSeason;
	
	private string _EStatus;
	
	private string _SubID;
	
	private string _Marks;
	
	private string _RStatus;
	
	private string _Session;
	
	private string _SID;
	
	private string _Course;
	
	private string _Part;
	
	public CPartII()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamSeason", DbType="NVarChar(50)")]
	public string ExamSeason
	{
		get
		{
			return this._ExamSeason;
		}
		set
		{
			if ((this._ExamSeason != value))
			{
				this._ExamSeason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EStatus", DbType="NVarChar(50)")]
	public string EStatus
	{
		get
		{
			return this._EStatus;
		}
		set
		{
			if ((this._EStatus != value))
			{
				this._EStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Marks
	{
		get
		{
			return this._Marks;
		}
		set
		{
			if ((this._Marks != value))
			{
				this._Marks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStatus", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
	public string RStatus
	{
		get
		{
			return this._RStatus;
		}
		set
		{
			if ((this._RStatus != value))
			{
				this._RStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Session
	{
		get
		{
			return this._Session;
		}
		set
		{
			if ((this._Session != value))
			{
				this._Session = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SID
	{
		get
		{
			return this._SID;
		}
		set
		{
			if ((this._SID != value))
			{
				this._SID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(50)")]
	public string Course
	{
		get
		{
			return this._Course;
		}
		set
		{
			if ((this._Course != value))
			{
				this._Course = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Part", DbType="NVarChar(50)")]
	public string Part
	{
		get
		{
			return this._Part;
		}
		set
		{
			if ((this._Part != value))
			{
				this._Part = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResultCPartI")]
public partial class ResultCPartI
{
	
	private int _SN;
	
	private string _SID;
	
	private string _SubID;
	
	private string _Marks;
	
	private string _Status;
	
	private string _Session;
	
	public ResultCPartI()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int SN
	{
		get
		{
			return this._SN;
		}
		set
		{
			if ((this._SN != value))
			{
				this._SN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SID
	{
		get
		{
			return this._SID;
		}
		set
		{
			if ((this._SID != value))
			{
				this._SID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string SubID
	{
		get
		{
			return this._SubID;
		}
		set
		{
			if ((this._SubID != value))
			{
				this._SubID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Marks
	{
		get
		{
			return this._Marks;
		}
		set
		{
			if ((this._Marks != value))
			{
				this._Marks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Session
	{
		get
		{
			return this._Session;
		}
		set
		{
			if ((this._Session != value))
			{
				this._Session = value;
			}
		}
	}
}
#pragma warning restore 1591
